[
    {
        "nome": "Andrea Luciana Sarah Novaes",
        "idade": 62,
        "cpf": "787.950.428-14",
        "rg": "46.568.959-0",
        "data_nasc": "1961-04-10",
        "sexo": "Feminino",
        "signo": "Libra",
        "mae": "Rita Daiane",
        "pai": "Fernando Murilo Anthony Novaes",
        "email": "andrealuciananovaes@outllok.com",
        "senha": "0Greawa5lE",
        "cep": "76812-716",
        "endereco": "Rua Aristides Haeffener",
        "numero": 735,
        "bairro": "Três Marias",
        "cidade": "Porto Velho",
        "estado": "RO",
        "telefone_fixo": "(69) 3800-0966",
        "celular": "(69) 98286-1953",
        "altura": "1,68",
        "peso": 87,
        "tipo_sanguineo": "B+",
        "cor": "roxo"
    },
    {
        "nome": "Leandro Francisco Melo",
        "idade": 71,
        "cpf": "041.240.625-08",
        "rg": "20.966.184-7",
        "data_nasc": "1952-08-10",
        "sexo": "Masculino",
        "signo": "Libra",
        "mae": "Gabriela Fabiana",
        "pai": "Enrico Henrique Renato Melo",
        "email": "leandro-melo76@jerasistemas.com.br",
        "senha": "2TxdxxNgqP",
        "cep": "72596-870",
        "endereco": "Travessa Salto do Céu",
        "numero": 815,
        "bairro": "Condomínio Residencial Santa Mônica (Santa Maria)",
        "cidade": "Brasília",
        "estado": "DF",
        "telefone_fixo": "(61) 3939-3899",
        "celular": "(61) 99571-6078",
        "altura": "1,71",
        "peso": 62,
        "tipo_sanguineo": "AB-",
        "cor": "vermelho"
    },
    {
        "nome": "Cristiane Isis Carvalho",
        "idade": 19,
        "cpf": "890.526.043-80",
        "rg": "16.529.850-9",
        "data_nasc": "2004-19-08",
        "sexo": "Feminino",
        "signo": "Leão",
        "mae": "Giovanna Kamilly Raimunda",
        "pai": "Carlos Guilherme Vitor Carvalho",
        "email": "cristiane-carvalho79@heinrich.com.br",
        "senha": "NznXmp392e",
        "cep": "79022-511",
        "endereco": "Praça Roger Assef Buainaim",
        "numero": 514,
        "bairro": "Monte Carlo",
        "cidade": "Campo Grande",
        "estado": "MS",
        "telefone_fixo": "(67) 2611-8823",
        "celular": "(67) 99444-2021",
        "altura": "1,62",
        "peso": 77,
        "tipo_sanguineo": "AB-",
        "cor": "roxo"
    },
    {
        "nome": "Carlos Eduardo Leandro das Neves",
        "idade": 22,
        "cpf": "604.619.056-80",
        "rg": "21.258.496-0",
        "data_nasc": "2001-23-02",
        "sexo": "Masculino",
        "signo": "Peixes",
        "mae": "Gabriela Sandra",
        "pai": "Sebastião Luan das Neves",
        "email": "carlos-dasneves99@riscao.com.br",
        "senha": "QEgOOunYka",
        "cep": "55021-415",
        "endereco": "Rua R-38",
        "numero": 438,
        "bairro": "Cidade Jardim",
        "cidade": "Caruaru",
        "estado": "PE",
        "telefone_fixo": "(81) 2540-1807",
        "celular": "(81) 98933-0715",
        "altura": "1,91",
        "peso": 77,
        "tipo_sanguineo": "A-",
        "cor": "azul"
    },
    {
        "nome": "Adriana Andrea Raimunda Almeida",
        "idade": 34,
        "cpf": "201.088.251-24",
        "rg": "34.512.911-8",
        "data_nasc": "1989-07-06",
        "sexo": "Feminino",
        "signo": "Gêmeos",
        "mae": "Lúcia Vera",
        "pai": "Ryan Juan Almeida",
        "email": "adriana_andrea_almeida@hotmmail.com",
        "senha": "NmjxBnSkjm",
        "cep": "95096-130",
        "endereco": "Rua Cambará do Sul",
        "numero": 292,
        "bairro": "Kayser",
        "cidade": "Caxias do Sul",
        "estado": "RS",
        "telefone_fixo": "(54) 3501-2728",
        "celular": "(54) 99802-6775",
        "altura": "1,61",
        "peso": 77,
        "tipo_sanguineo": "O-",
        "cor": "vermelho"
    },
    {
        "nome": "Breno Alexandre Benjamin Cavalcanti",
        "idade": 54,
        "cpf": "750.188.456-00",
        "rg": "30.347.798-2",
        "data_nasc": "1969-23-01",
        "sexo": "Masculino",
        "signo": "Aquário",
        "mae": "Rayssa Alessandra Yasmin",
        "pai": "César Thomas Cavalcanti",
        "email": "breno.alexandre.cavalcanti@lins.net.br",
        "senha": "bcdThQrxO0",
        "cep": "69307-595",
        "endereco": "Rua Arapari",
        "numero": 283,
        "bairro": "Caçari",
        "cidade": "Boa Vista",
        "estado": "RR",
        "telefone_fixo": "(95) 3652-9420",
        "celular": "(95) 99266-4088",
        "altura": "1,72",
        "peso": 83,
        "tipo_sanguineo": "O-",
        "cor": "laranja"
    },
    {
        "nome": "Mateus Luís Rezende",
        "idade": 64,
        "cpf": "841.532.738-21",
        "rg": "50.567.933-4",
        "data_nasc": "1959-04-07",
        "sexo": "Masculino",
        "signo": "Câncer",
        "mae": "Sabrina Maya Lara",
        "pai": "Leonardo Francisco Antonio Rezende",
        "email": "mateus_rezende@onvale.com",
        "senha": "z9IzkeoS21",
        "cep": "57042-310",
        "endereco": "Rua Emerentino Costa",
        "numero": 449,
        "bairro": "Feitosa",
        "cidade": "Maceió",
        "estado": "AL",
        "telefone_fixo": "(82) 3664-0548",
        "celular": "(82) 99537-8524",
        "altura": "1,69",
        "peso": 80,
        "tipo_sanguineo": "B-",
        "cor": "vermelho"
    },
    {
        "nome": "Carla Esther Rosângela Souza",
        "idade": 22,
        "cpf": "841.527.400-94",
        "rg": "27.225.427-7",
        "data_nasc": "2001-22-06",
        "sexo": "Feminino",
        "signo": "Câncer",
        "mae": "Bruna Emily",
        "pai": "Arthur Enrico Souza",
        "email": "carla-souza76@lbrazil.com.br",
        "senha": "8Nqbl3nk5l",
        "cep": "26160-330",
        "endereco": "Avenida Creuza de Lima",
        "numero": 157,
        "bairro": "Nova Aurora",
        "cidade": "Belford Roxo",
        "estado": "RJ",
        "telefone_fixo": "(21) 3682-6965",
        "celular": "(21) 98716-4389",
        "altura": "1,54",
        "peso": 90,
        "tipo_sanguineo": "B+",
        "cor": "vermelho"
    },
    {
        "nome": "Elza Isis de Paula",
        "idade": 28,
        "cpf": "096.366.386-08",
        "rg": "47.498.585-4",
        "data_nasc": "1995-19-05",
        "sexo": "Feminino",
        "signo": "Touro",
        "mae": "Rita Rayssa Gabriela",
        "pai": "Lucas César de Paula",
        "email": "elza-depaula82@spamgourmet.com",
        "senha": "cMmnxY82z9",
        "cep": "65049-231",
        "endereco": "Rua Um",
        "numero": 923,
        "bairro": "Conjunto Cial",
        "cidade": "São Luís",
        "estado": "MA",
        "telefone_fixo": "(98) 2991-9739",
        "celular": "(98) 98691-6484",
        "altura": "1,69",
        "peso": 50,
        "tipo_sanguineo": "AB-",
        "cor": "vermelho"
    },
    {
        "nome": "Rafaela Luzia Pereira",
        "idade": 67,
        "cpf": "464.866.500-79",
        "rg": "35.834.678-2",
        "data_nasc": "1956-12-10",
        "sexo": "Feminino",
        "signo": "Libra",
        "mae": "Flávia Cecília Hadassa",
        "pai": "Yago Kauê Pereira",
        "email": "rafaela.luzia.pereira@valdulion.com.br",
        "senha": "Q56cah3yYg",
        "cep": "60340-040",
        "endereco": "Vila Santa Cláudia",
        "numero": 977,
        "bairro": "Jardim Iracema",
        "cidade": "Fortaleza",
        "estado": "CE",
        "telefone_fixo": "(85) 2696-6380",
        "celular": "(85) 98483-2597",
        "altura": "1,71",
        "peso": 88,
        "tipo_sanguineo": "A-",
        "cor": "vermelho"
    },
    {
        "nome": "Pietra Tatiane Isabelle da Conceição",
        "idade": 68,
        "cpf": "178.979.107-33",
        "rg": "36.184.790-7",
        "data_nasc": "1955-03-02",
        "sexo": "Feminino",
        "signo": "Aquário",
        "mae": "Amanda Natália",
        "pai": "Raimundo Osvaldo da Conceição",
        "email": "pietra_tatiane_daconceicao@resource.com.br",
        "senha": "SLpBzPNfIj",
        "cep": "77020-130",
        "endereco": "Quadra 110 Sul Avenida NS 10",
        "numero": 500,
        "bairro": "Plano Diretor Sul",
        "cidade": "Palmas",
        "estado": "TO",
        "telefone_fixo": "(63) 3905-6997",
        "celular": "(63) 99695-6652",
        "altura": "1,63",
        "peso": 69,
        "tipo_sanguineo": "B+",
        "cor": "roxo"
    },
    {
        "nome": "Oliver César Moura",
        "idade": 57,
        "cpf": "650.897.837-30",
        "rg": "30.031.576-4",
        "data_nasc": "1966-20-04",
        "sexo": "Masculino",
        "signo": "Áries",
        "mae": "Valentina Mariah Regina",
        "pai": "Pietro Diogo Moura",
        "email": "oliver_moura@vivo.com.br",
        "senha": "ErpUPSP8dW",
        "cep": "58706-006",
        "endereco": "Rua Sargento Miguelzinho",
        "numero": 543,
        "bairro": "São Sebastião",
        "cidade": "Patos",
        "estado": "PB",
        "telefone_fixo": "(83) 3954-8094",
        "celular": "(83) 99104-2442",
        "altura": "1,79",
        "peso": 53,
        "tipo_sanguineo": "O-",
        "cor": "preto"
    },
    {
        "nome": "Giovanni Felipe Geraldo Porto",
        "idade": 75,
        "cpf": "701.501.894-27",
        "rg": "24.488.929-6",
        "data_nasc": "1948-06-10",
        "sexo": "Masculino",
        "signo": "Libra",
        "mae": "Giovanna Beatriz Emilly",
        "pai": "Ricardo Heitor Breno Porto",
        "email": "giovannifelipeporto@comercialrizzo.com",
        "senha": "HoLMQmq0Gd",
        "cep": "66617-200",
        "endereco": "Rua Cuiabá",
        "numero": 694,
        "bairro": "Val-de-Cães",
        "cidade": "Belém",
        "estado": "PA",
        "telefone_fixo": "(91) 2804-0567",
        "celular": "(91) 99443-7445",
        "altura": "1,75",
        "peso": 70,
        "tipo_sanguineo": "A-",
        "cor": "preto"
    },
    {
        "nome": "Heitor Martin José da Cruz",
        "idade": 57,
        "cpf": "374.279.500-70",
        "rg": "16.225.652-8",
        "data_nasc": "1966-19-09",
        "sexo": "Masculino",
        "signo": "Virgem",
        "mae": "Camila Adriana Gabrielly",
        "pai": "Oliver Benjamin Julio da Cruz",
        "email": "heitor-dacruz79@schaeffler.com",
        "senha": "GkeS3KcKK7",
        "cep": "79620-168",
        "endereco": "Travessa 120",
        "numero": 163,
        "bairro": "Nossa Senhora Aparecida",
        "cidade": "Três Lagoas",
        "estado": "MS",
        "telefone_fixo": "(67) 3577-9990",
        "celular": "(67) 98779-5305",
        "altura": "1,76",
        "peso": 59,
        "tipo_sanguineo": "B+",
        "cor": "amarelo"
    },
    {
        "nome": "Lara Fernanda Assis",
        "idade": 44,
        "cpf": "043.310.252-76",
        "rg": "10.167.803-4",
        "data_nasc": "1979-07-06",
        "sexo": "Feminino",
        "signo": "Gêmeos",
        "mae": "Mariah Milena",
        "pai": "Bryan Mateus Arthur Assis",
        "email": "larafernandaassis@atualmarcenaria.com.br",
        "senha": "21OMWzFi65",
        "cep": "09405-340",
        "endereco": "Rua São Vicente",
        "numero": 525,
        "bairro": "Colônia",
        "cidade": "Ribeirão Pires",
        "estado": "SP",
        "telefone_fixo": "(11) 3997-5770",
        "celular": "(11) 98776-4797",
        "altura": "1,67",
        "peso": 82,
        "tipo_sanguineo": "B+",
        "cor": "vermelho"
    },
    {
        "nome": "Luiza Mariane da Costa",
        "idade": 25,
        "cpf": "603.018.005-37",
        "rg": "13.750.347-7",
        "data_nasc": "1998-18-01",
        "sexo": "Feminino",
        "signo": "Capricórnio",
        "mae": "Manuela Amanda Gabriela",
        "pai": "Kevin Augusto Marcos da Costa",
        "email": "luiza_mariane_dacosta@iclaud.com",
        "senha": "ZsLuA6yLAm",
        "cep": "91250-323",
        "endereco": "Rua Capricórnio",
        "numero": 359,
        "bairro": "Rubem Berta",
        "cidade": "Porto Alegre",
        "estado": "RS",
        "telefone_fixo": "(51) 2583-4705",
        "celular": "(51) 99554-9131",
        "altura": "1,80",
        "peso": 63,
        "tipo_sanguineo": "AB+",
        "cor": "roxo"
    },
    {
        "nome": "Daiane Sophia Rebeca da Luz",
        "idade": 72,
        "cpf": "516.115.614-77",
        "rg": "47.840.272-7",
        "data_nasc": "1951-12-02",
        "sexo": "Feminino",
        "signo": "Aquário",
        "mae": "Maya Marli Camila",
        "pai": "Pietro Emanuel João da Luz",
        "email": "daianesophiadaluz@lhp.com.br",
        "senha": "0eIziFqGOj",
        "cep": "60410-250",
        "endereco": "Vila Roberto",
        "numero": 505,
        "bairro": "Montese",
        "cidade": "Fortaleza",
        "estado": "CE",
        "telefone_fixo": "(85) 3728-7317",
        "celular": "(85) 98944-6891",
        "altura": "1,79",
        "peso": 84,
        "tipo_sanguineo": "A+",
        "cor": "azul"
    },
    {
        "nome": "Jennifer Tatiane Nogueira",
        "idade": 62,
        "cpf": "350.834.957-83",
        "rg": "20.626.665-0",
        "data_nasc": "1961-04-09",
        "sexo": "Feminino",
        "signo": "Virgem",
        "mae": "Bárbara Marina",
        "pai": "Benedito Nicolas Kaique Nogueira",
        "email": "jennifer-nogueira78@cincoentretenimentos.com.br",
        "senha": "cMjrRu99yP",
        "cep": "63100-538",
        "endereco": "Rua Monsenhor Tavares",
        "numero": 418,
        "bairro": "Palmeiral",
        "cidade": "Crato",
        "estado": "CE",
        "telefone_fixo": "(88) 2754-8994",
        "celular": "(88) 98683-6761",
        "altura": "1,50",
        "peso": 79,
        "tipo_sanguineo": "B+",
        "cor": "preto"
    },
    {
        "nome": "Stefany Natália Patrícia Oliveira",
        "idade": 29,
        "cpf": "202.269.785-59",
        "rg": "34.029.241-6",
        "data_nasc": "1994-13-09",
        "sexo": "Feminino",
        "signo": "Virgem",
        "mae": "Sabrina Isadora",
        "pai": "Ricardo Francisco Renato Oliveira",
        "email": "stefany.natalia.oliveira@multmed.com.br",
        "senha": "WypY9zAKKa",
        "cep": "68035-342",
        "endereco": "Beco da Paz",
        "numero": 886,
        "bairro": "Santarenzinho",
        "cidade": "Santarém",
        "estado": "PA",
        "telefone_fixo": "(93) 3692-0071",
        "celular": "(93) 99539-8438",
        "altura": "1,77",
        "peso": 90,
        "tipo_sanguineo": "O+",
        "cor": "laranja"
    },
    {
        "nome": "Pietra Cristiane Sarah Jesus",
        "idade": 34,
        "cpf": "369.899.788-64",
        "rg": "43.178.186-2",
        "data_nasc": "1989-11-10",
        "sexo": "Feminino",
        "signo": "Libra",
        "mae": "Débora Clara",
        "pai": "Erick Leandro Jesus",
        "email": "pietra.cristiane.jesus@facebook.com",
        "senha": "F74fRkwLO2",
        "cep": "49044-200",
        "endereco": "Rua Capitanias Hereditárias",
        "numero": 441,
        "bairro": "Santa Maria",
        "cidade": "Aracaju",
        "estado": "SE",
        "telefone_fixo": "(79) 2940-3390",
        "celular": "(79) 99558-4980",
        "altura": "1,64",
        "peso": 65,
        "tipo_sanguineo": "A+",
        "cor": "roxo"
    },
    {
        "nome": "Tomás Kevin Rodrigo Ribeiro",
        "idade": 28,
        "cpf": "840.700.983-05",
        "rg": "23.367.605-3",
        "data_nasc": "1995-02-05",
        "sexo": "Masculino",
        "signo": "Touro",
        "mae": "Carla Bianca Daniela",
        "pai": "Pedro Henrique Mateus Ribeiro",
        "email": "tomas.kevin.ribeiro@band.com",
        "senha": "2b34pcf3zZ",
        "cep": "60331-150",
        "endereco": "Vila Areado",
        "numero": 178,
        "bairro": "Barra do Ceará",
        "cidade": "Fortaleza",
        "estado": "CE",
        "telefone_fixo": "(85) 3746-1495",
        "celular": "(85) 99981-3185",
        "altura": "1,70",
        "peso": 55,
        "tipo_sanguineo": "A-",
        "cor": "azul"
    },
    {
        "nome": "Gabrielly Sandra Castro",
        "idade": 60,
        "cpf": "975.610.262-42",
        "rg": "17.938.091-6",
        "data_nasc": "1963-27-01",
        "sexo": "Feminino",
        "signo": "Aquário",
        "mae": "Alice Helena",
        "pai": "Nathan Kevin Castro",
        "email": "gabrielly_sandra_castro@iq.unesp.br",
        "senha": "o5eeULi5X8",
        "cep": "30870-330",
        "endereco": "Rua Passo Fundo",
        "numero": 848,
        "bairro": "Novo Glória",
        "cidade": "Belo Horizonte",
        "estado": "MG",
        "telefone_fixo": "(31) 3558-4227",
        "celular": "(31) 98816-7192",
        "altura": "1,58",
        "peso": 54,
        "tipo_sanguineo": "B+",
        "cor": "roxo"
    },
    {
        "nome": "Andreia Isis Peixoto",
        "idade": 76,
        "cpf": "888.754.292-94",
        "rg": "10.518.947-9",
        "data_nasc": "1947-16-03",
        "sexo": "Feminino",
        "signo": "Peixes",
        "mae": "Lavínia Catarina",
        "pai": "Isaac Cauê Peixoto",
        "email": "andreia_isis_peixoto@candello.abv.br",
        "senha": "kL3LGMS7k9",
        "cep": "95110-633",
        "endereco": "Rua Jair Antônio Alves",
        "numero": 236,
        "bairro": "Desvio Rizzo",
        "cidade": "Caxias do Sul",
        "estado": "RS",
        "telefone_fixo": "(54) 2690-2367",
        "celular": "(54) 98922-8239",
        "altura": "1,80",
        "peso": 85,
        "tipo_sanguineo": "AB+",
        "cor": "vermelho"
    },
    {
        "nome": "Joaquim Isaac Campos",
        "idade": 79,
        "cpf": "427.386.792-34",
        "rg": "37.301.769-8",
        "data_nasc": "1944-04-04",
        "sexo": "Masculino",
        "signo": "Áries",
        "mae": "Aline Heloise Bruna",
        "pai": "Julio Caleb Pedro Henrique Campos",
        "email": "joaquim-campos82@termakui.com.br",
        "senha": "r3W3BMFLzz",
        "cep": "58300-045",
        "endereco": "Travessa Ivo Borges",
        "numero": 857,
        "bairro": "Centro",
        "cidade": "Santa Rita",
        "estado": "PB",
        "telefone_fixo": "(83) 2595-2006",
        "celular": "(83) 99593-3203",
        "altura": "1,76",
        "peso": 61,
        "tipo_sanguineo": "B+",
        "cor": "vermelho"
    },
    {
        "nome": "Juliana Rayssa da Silva",
        "idade": 30,
        "cpf": "425.569.682-90",
        "rg": "23.459.740-9",
        "data_nasc": "1993-19-02",
        "sexo": "Feminino",
        "signo": "Aquário",
        "mae": "Isabel Cecília Heloise",
        "pai": "Breno Fernando da Silva",
        "email": "juliana_dasilva@oerlikon.com",
        "senha": "A2m2AgR1Ir",
        "cep": "69309-460",
        "endereco": "Rua Azaléias",
        "numero": 902,
        "bairro": "Pricumã",
        "cidade": "Boa Vista",
        "estado": "RR",
        "telefone_fixo": "(95) 3933-9176",
        "celular": "(95) 98349-0866",
        "altura": "1,75",
        "peso": 77,
        "tipo_sanguineo": "AB+",
        "cor": "vermelho"
    },
    {
        "nome": "Yago Marcos Ramos",
        "idade": 48,
        "cpf": "994.827.878-03",
        "rg": "31.966.485-5",
        "data_nasc": "1975-16-10",
        "sexo": "Masculino",
        "signo": "Libra",
        "mae": "Giovana Antonella",
        "pai": "Matheus Cauê Ruan Ramos",
        "email": "yagomarcosramos@bluewash.com.br",
        "senha": "4RJjg4Bs6I",
        "cep": "74369-515",
        "endereco": "Rua Elche",
        "numero": 417,
        "bairro": "Setor Três Marias",
        "cidade": "Goiânia",
        "estado": "GO",
        "telefone_fixo": "(62) 2562-7940",
        "celular": "(62) 99617-5870",
        "altura": "1,61",
        "peso": 80,
        "tipo_sanguineo": "A-",
        "cor": "roxo"
    },
    {
        "nome": "Marcos Vinicius Caio da Rocha",
        "idade": 21,
        "cpf": "978.124.683-99",
        "rg": "12.195.121-2",
        "data_nasc": "2002-17-06",
        "sexo": "Masculino",
        "signo": "Gêmeos",
        "mae": "Márcia Bárbara Isabella",
        "pai": "Enzo Miguel da Rocha",
        "email": "marcos_vinicius_darocha@cartovale.com.br",
        "senha": "oxDWW7zyBK",
        "cep": "50970-150",
        "endereco": "Rua Professor Otávio Tavares",
        "numero": 535,
        "bairro": "Várzea",
        "cidade": "Recife",
        "estado": "PE",
        "telefone_fixo": "(81) 3760-5199",
        "celular": "(81) 98190-8964",
        "altura": "1,96",
        "peso": 108,
        "tipo_sanguineo": "A+",
        "cor": "azul"
    },
    {
        "nome": "Francisco Bruno Manoel Farias",
        "idade": 52,
        "cpf": "669.004.842-04",
        "rg": "15.922.836-0",
        "data_nasc": "1971-20-08",
        "sexo": "Masculino",
        "signo": "Leão",
        "mae": "Isis Lúcia Juliana",
        "pai": "José Benício Vinicius Farias",
        "email": "francisco_bruno_farias@fojsc.unesp.br",
        "senha": "Uo3a48WbCt",
        "cep": "88803-609",
        "endereco": "Rua Recanto das Flores",
        "numero": 547,
        "bairro": "Recanto Verde",
        "cidade": "Criciúma",
        "estado": "SC",
        "telefone_fixo": "(48) 3836-0958",
        "celular": "(48) 99633-2688",
        "altura": "1,93",
        "peso": 95,
        "tipo_sanguineo": "AB+",
        "cor": "roxo"
    },
    {
        "nome": "Victor Lorenzo Costa",
        "idade": 47,
        "cpf": "676.196.171-83",
        "rg": "31.745.248-4",
        "data_nasc": "1976-05-07",
        "sexo": "Masculino",
        "signo": "Câncer",
        "mae": "Joana Marina Fabiana",
        "pai": "Danilo Benjamin Vicente Costa",
        "email": "victor-costa91@premierpet.com.br",
        "senha": "wSSu4l2rlB",
        "cep": "49044-322",
        "endereco": "Rua Eurico Luiz dos Santos",
        "numero": 324,
        "bairro": "Santa Maria",
        "cidade": "Aracaju",
        "estado": "SE",
        "telefone_fixo": "(79) 3565-7109",
        "celular": "(79) 98733-5069",
        "altura": "1,73",
        "peso": 93,
        "tipo_sanguineo": "B-",
        "cor": "preto"
    },
    {
        "nome": "Cláudio Enzo Fogaça",
        "idade": 20,
        "cpf": "639.658.382-88",
        "rg": "30.618.189-7",
        "data_nasc": "2003-11-08",
        "sexo": "Masculino",
        "signo": "Leão",
        "mae": "Ana Mariah",
        "pai": "Pietro Geraldo Fogaça",
        "email": "claudio_fogaca@dlh.de",
        "senha": "Oti36XPsh9",
        "cep": "78730-112",
        "endereco": "Rua Paulo VI",
        "numero": 281,
        "bairro": "Jardim Gloria",
        "cidade": "Rondonópolis",
        "estado": "MT",
        "telefone_fixo": "(66) 3916-5411",
        "celular": "(66) 98899-6765",
        "altura": "1,92",
        "peso": 52,
        "tipo_sanguineo": "O+",
        "cor": "preto"
    }
]